/**:
  psdk_wrapper_node:
    ros__parameters:
      app_name: "TestPSDK"
      app_id: "***REMOVED***"
      app_key: "***REMOVED***"
      app_license: "***REMOVED***"
      developer_account: "developer_account"
      baudrate: "921600"
      hardware_connection: "DJI_USE_UART_AND_USB_BULK_DEVICE"
      uart_dev_1: "/dev/dji_serial"
      uart_dev_2: "/dev/dji_advanced_sensing"
  
      data_frequency: # Options are: 1, 5, 10, 50, 100, 200, 400 Hz 
        imu: 100
        attitude: 100
        acceleration: 50
        velocity: 50
        angular_velocity: 100
        position: 50
        gps_data: 1
        rtk_data: 1
        magnetometer: 50
        rc_channels_data: 1
        gimbal_data: 1
        flight_status: 1
        battery_level: 1
        control_information: 50
      
      camera:
        streaming_path: "/mystream"
        streaming_port: "8554"



