name: Build

on: 
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  industrial_ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: psdk_ros2
      - uses: 'ros-industrial/industrial_ci@master'
        env:
          ROS_DISTRO: humble
          ROS_REPO: main
          ADDITIONAL_DEBS: git
          NOT_TEST_BUILD: true
