name: Build

on: 
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build_debians:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: psdk_ros2
      - uses: actions/checkout@v4
        with:
          repository: dji-sdk/Payload-SDK
          ref: 3.5
          path: Payload-SDK
      - name: ROS 2 Build Debian Package
        run: |
         sudo apt update && sudo apt install -y python3-pip dpkg-dev debhelper dh-python libopus-dev ffmpeg libavcodec-dev libavformat-dev libavfilter-dev
         ln -snf /usr/lib/x86_64-linux-gnu/libopus.a /usr/local/lib
         sudo pip3 install rosdep bloom
         sudo rosdep init
         echo "yaml file:///rosdep.yaml" >> 50-my-packages.list
         sudo mv 50-my-packages.list /etc/ros/rosdep/sources.list.d
         echo "psdk_interfaces:\n  ubuntu: [ros-humble-psdk-interfaces]" >> rosdep.yaml
         sudo mv rosdep.yaml /
         sudo rosdep update
         cd psdk_ros2/psdk_interfaces 
         bloom-generate rosdebian --ros-distro humble
         debian/rules "binary --parallel --dpkg-shlibdeps-params=--ignore-missing-info"
         ls ..
         