name: Build

on: 
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build_debians:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: psdk_ros2
      - uses: actions/checkout@v4
        with:
          repository: dji-sdk/Payload-SDK
          ref: 3.5
          path: Payload-SDK
      - name: ROS 2 Build Debian Package
        run: |
         sudo apt update && sudo apt install -y python3-pip dpkg-dev debhelper dh-python && pip3 install rosdep bloom
         rosdep init
         echo "yaml file:///rosdep.yaml" >> /etc/ros/rosdep/sources.list.d/50-my-packages.list
         echo "psdk_interfaces:\n  ubuntu: [ros-humble-psdk-interfaces]" >> /rosdep.yaml
         rosdep update
